### PR TITLE
Reworked all the basic projects

### PR DESCRIPTION
**Pull request by pBouillon**
- [x] switched to Python 3
- [x] added comments as specified in the Google StyleGuide
- [x] added imports as specified in the Google StyleGuide

### CODE REVIEW

**Comment by pBouillon** [comment]
I'll work on the conflicts

**Comment by harryjas** [comment]
Rebase and you are GTG

**Comment by harryjas** [comment]
Rebase to resolve conflicts

**Comment by pBouillon** [comment]
@Marwan2001 @harryjas All good !

**Pull request merged**
